name: CI

on:
  pull_request:

jobs:
  lint-and-typecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with:
          version: 10.5.2
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm
      - name: Install dependencies
        run: pnpm install
      - name: Lint
        run: pnpm lint
      - name: Typecheck
        run: pnpm typecheck
      - name: Build
        run: pnpm build
      - name: Test
        run: pnpm test
        env:
          NEXTAUTH_SECRET: testingsecret_shhh_32chars_min
          DATABASE_URL: postgres://user:pass@localhost:5432/testdb
          AUTH_EMAIL_ENABLED: "false"
          NEXT_PUBLIC_VIDEO_PROVIDER_DEFAULT: youtube
          NEXT_PUBLIC_TELEMETRY_DEBUG: "0"
      - name: Verify database migrations (dry run)
        run: pnpm db:deploy -- --dry-run
        env:
          DATABASE_URL: postgres://user:pass@localhost:5432/dummydb
